### ISSUE TITLE
[FEATURE] Activate Depandabot

### ISSUE THREAD

**Issue by Jonasvdbo** [alliander-opensource/weather-provider-api#58]
**Is your feature request related to a problem? Please describe.**
Make it easier to maintain your dependencies

**Describe the solution you'd like**
Dependabot takes the effort out of maintaining your dependencies. You can use it to ensure that your repository automatically keeps up with the latest releases of the packages and applications it depends on.

You enable Dependabot version updates by checking a configuration file into your repository. The configuration file specifies the location of the manifest, or of other package definition files, stored in your repository. Dependabot uses this information to check for outdated packages and applications. Dependabot determines if there is a new version of a dependency by looking at the semantic versioning ([semver](https://semver.org/)) of the dependency to decide whether it should update to that version.

**Describe alternatives you've considered**
Alternative is to do it mannually. 

**Additional context**
For more information see: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates

Also github support Dependabot, see: https://github.com/alliander-opensource/power-grid-model/network/updates

**Comment by rflinnenbank** [comment]
With the current set-up switching to the automated Dependabot still feels quite risky.

There have been a number of situations where security suggestions by Dependabot ended up with combinations of versions that do not perform well together. Most notable was a version upgrade that boosted **pandas** and **numpy** to versions that would generate errors when combined in that way for exactly the type of interactions we used. 

Automated updates would therefor only be acceptable within the following boundaries:

- The automated updates should results in a versioning pattern that easily distinguishes the automated update from regular updates. Possibly a suffix?
- The automated updates should be passing a full and complete testing suite before merging is allowed, to make sure everything still operates as it should.
- The automated updates would be incorporated into the regular updates after manually validating and testing them for version interaction problems. This could be by either adding them to the next regular update, or in the case of multiple automated updates by grouping them together into a single "version fix" update.

As of now, the version 2.x releases don't have the full and complete unit test package needed to allow for this process to be done automatically. 

As such, version 2.x will be manually updated if needed, and this feature request will be added to version 3.x development instead.

**Comment by rflinnenbank** [comment]
With DCO now already as a required check for each pull request and version, and Poetry governing updates it is best to keep Dependabot's suggestions as they are and leave the updates to Poetry instead.
